# Generated by Django 4.1.5 on 2023-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('nascimento', models.DateField()),
                ('telefones', models.TextField()),
                ('responsavel', models.TextField()),
            ],
        ),
    ]
