# Generated by Django 4.1.5 on 2023-01-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='enderecos',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
