# Generated by Django 4.1.5 on 2023-01-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_enderecos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_matricula', models.DateTimeField()),
                ('ano_vigencia', models.IntegerField()),
                ('dia_vencimento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('valores_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano_vigencia', models.IntegerField()),
                ('ano_escolar', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='bolsa_desconto',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('mensalidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_viigencia', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.matricula')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='mensalidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.valores'),
        ),
    ]
