# Generated by Django 4.1.5 on 2023-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_matricula_valores_aluno_bolsa_desconto_mensalidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='bolsa_desconto',
        ),
        migrations.AddField(
            model_name='matricula',
            name='bolsa_desconto',
            field=models.IntegerField(default=0),
        ),
    ]
