# Generated by Django 4.1.5 on 2023-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_remove_aluno_bolsa_desconto_matricula_bolsa_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
